<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        &copy; {{ moment(Date.now()).year() }} <strong>Building The Future Now</strong> by LA COiL and Another Politics is Possible (APP).
      </p>
      <p><a href="https://twitter.com/{{ config.twitter }}" class="footer-link" target="_blank"><i class="fa fa-twitter"></i></a></p>
    </div>
  </div>
</footer>
